apiVersion: v1 
kind: ConfigMap 
metadata:
  name: demo-app-configmap
  labels:
    app: demo-app-stack 
    environment: dev
data:
  # Configuration values can be set as key-value properties
  intg_database_name: INTG
  intg_database_driver: org.postgresql.Driver
  intg_database_uri: jdbc:postgresql://pgintg-db-rw.dbf.nafleetdev.ue1.wexglobal.com:5432/pgdbfintg
  
  # Or set as complete file contents
  oauth.conf: | 
    oauth.resourceid=auth-demo-service
    oauth.hostname=https://auth.demoapps.com
    