apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-app
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: demo-driver-service
          image: "leod/driver-service:0.0.6"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8101
          env:
            - name: Environment
              value: test
            - name: Service_Version
              value: 0.0.6
            - name: App_Token
              valueFrom:
                secretKeyRef:
                  name: demo-service-secret
                  key: TEST_TOKEN
          envFrom:
            - configMapRef:
                name: demo-service-configmap
    
