apiVersion: v1
kind: Service
metadata:
  name: demoapp-service
spec:
  selector:
    app: demo-app
  ports:
    - protocol: TCP
      port: 8101
      targetPort: 8101
      nodePort: 31001
  type: NodePort
