apiVersion: v1
kind: Service
metadata:
  name: python-app-service
spec:
  selector:
    app: python-app
  ports:
    - protocol: TCP
      port: 8050
      targetPort: 8050
      nodePort: 31002
  type: NodePort
